# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f15f16d5acc2b2c0c6fe321769b39efb2b36b573e222bfaf0043846c36d5bb44883334d4446de2a40858088bd3546cd90a08dd8e1c3a764d286c5374b3505f5

test:
  secret_key_base: affefa7eb2167923c8cb1974e7bf2587b12564ad2956277281871602521927031a6a4e8aa5c31c92283abc3b438d9d675e3868f621e97ba33897e7389e5bb890

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
